language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - "ci/build.sh"

# command to run tests
script:
  - "ci/test.sh"
  - "codeclimate-test-reporter"
after_success:
  - bash <(curl -s https://codecov.io/bash)