language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

services:
  - couchdb

install:
  - "ci/build.sh"
  - "ci/install.sh"

script:
  - "ci/test.sh"

after_success:
  - "codeclimate-test-reporter"
  - bash <(curl -s https://codecov.io/bash)
  - coveralls
