language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - "ci/build.sh"

# command to run tests
script:
  - "pip install -r requirements.pip"
  - "ci/local_install_test.sh"
  - "ci/local_rest_test.sh"

after_success:
  - "codeclimate-test-reporter"
  - bash <(curl -s https://codecov.io/bash)
  - coveralls
