language: python
python:
- '3.3'
- '3.4'
- '3.5'
- nightly
deploy:
  provider: pypi
  password:
    secure: GUx2P4I86gaRCn6jtDnuCoL7sYrsQM2f66J0o+W1hlrWr6/vIkGlM1d9oI+rK5gsrV8MEVWGlZbi7ALfG14z5DGzhvkAcpphYu8H9I6cQUHLylAy+ZulpbIFoLAtZV3+d12i5DFbbQh1SHkrdHfZEAlNzgjSeNDBNHJHe+M8MX+u/+Sc8eheUfP31n/tVz62vz6duhxn1JTGvkLFAw4Euz5oDZvUfNAVuU3LZvF3VNAerlLUBlrxsVpF+hYBBSQCu2M1AtnNFws6qM86LXMNPZw/+QErg33ybvNJxRy2n8ba5GOLTPexSrZllElJIEvaiD1BrIfLd2zgcl4c7ail1n+ZQVnaeLgLxIqyLUOPZNJlJlEuhGTii8H5a3PXpHMomukqmUlDw9TveihX89KHvJaOnhnko7t5B+yWe1ZMZtvbNQWzCt/4D1UomZnp0u/PPIGqirLlaOnMfwChpPuEs+Is+I8S9xwHlLAybh7JFaFu8iH9MI/04xAnn+rL9LsclG4UqYAF3oSNY0LsT2/bUUNKLgHLt7C4CURGHYDlJgOMAioC+EJm/trim6n+dZewWH0/B9bzIv/EXO1+pFXcoTU/dqL3+IDAfca+HncwHDKCEHtlJddDIhCGp495CqwojGu6KZpBFq3S9zvbsnA19CNRrLGq5HT2y6ufAEizUjA=
  username:
    secure: hB/b1Fds4ZlFzqLOZ+S3byPffZ4BuNPHYrvzBNMAElt1ejJ2GMbh9Ztt+sBa2BDTGX6NRgwhXRYJiQcx2o95TWkS1owcsNoZlS81XXYrSHby6UojaRSGxBpuzBGPNvnCvyMz9DrWwLFKu0GwGCMUO8eK11Q49PBJalV6jpj9KKaN33Ks+4nfNGnEM8SPy6nhg/P6tr37WO3MlJ8f83BVDfWwrorykNCQt0DvLm5YTpzhSA38rYUijb+XRXMaz7Dz+4dww5zqKctssVV6LRt7lsRTuCYITF+lNAVcCpPaLHltQnJvJ+zY1zDoTucK+wAWHQQ4SfrIvS2aw2z+sxwCQIdo1+dZFP79zkzKXq6NUd99Cx17vX5Kvih7ode5c2KpBiPqxm7EmxL7FxtcdOrI0LrXidEzHO4AuTTR1+QFBN7BfCCEKMPTeVnsHQROdgXX8AFqNjrEEFX0VhYeTm6aT+d5rEC4WHXetM4dgZBgfVeesC0LgRnTlesB44rZKy0wueusgMT+tQWp3RAB+Obndo9PwW8Rc9eUm3eBMmx/iy0C2LaQ+zxhOKp0LDTcDrhQMNopec/jYXkWhpc2DsA6Y87vUYm+aTYQ7midumymPOpXkW4wAVuqDyOxCQFZEpBwVmbvZzmvZuAKJMCz5JfUFzSEyOseaqWnk0q3E6nyK2I=
services:
- couchdb
install:
- ci/build.sh
- ci/install.sh
script:
- ci/test.sh
after_success:
- codeclimate-test-reporter
- bash <(curl -s https://codecov.io/bash)
- coveralls
