language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - "./build.sh"

# command to run tests
# script:
