language: python
python:
- '3.3'
before_deploy:
- ci/build.sh
- ls
deploy:
  skip_cleanup: true
  provider: pypi
  user: manoelhc
  password:
    secure: 
  on:
    distributions: sdist bdist_wheel
    repo: manoelhc/restafari
services:
- couchdb
install:
- ci/build.sh
- ci/install.sh
script:
- ci/test.sh
after_success:
- codeclimate-test-reporter
- bash <(curl -s https://codecov.io/bash)
- coveralls
- codecov
