tests:
  - id : ping
    weight : 20
    executable : true
    exec_before : []
    exec_after : []
    desc : "This is the ping"
    format : "json"
    path :  "/files/pnass/simple_comparison"
    method : GET
    expect:
      http: 200
      data:
        time :
          $and:
             $or :
               $type : Number
               $gt : 10000
          $or :
             $lt : 2000
             $gt : 100
